### ISSUE TITLE
Develop the User Interface for Signup Page

### ISSUE THREAD

**Issue by Endework** [Endework/SEETHIO_LIVE#1]

**Comment by oly-baby** [comment]
@Endework 
pls add description to this isssue

**Comment by Endework** [comment]
Description:
Branch: **front-end**
We need to develop the user interface for the signup page:

1. **Develop the user interface for signup**: Create a user-friendly and intuitive signup page where users can enter their details to create an account.

2. **Develop the user interface for email verification**: After signing up, users should be directed to a page where they can enter the 8-digit code they received in their email for verification.

3. **Develop the user interface for successful email verification**: Once the email is verified, users should see a page confirming that their email has been successfully verified and their account has been created.

Deadline: 10/27/2023

**Comment by Endework** [comment]
> @Endework pls add description to this isssue

Done

**Comment by Endework** [comment]
Completed
