### ISSUE TITLE
push the landing page file to frontend folder

### ISSUE THREAD

**Issue by oly-baby** [Endework/SEETHIO_LIVE#18]
The landing page file which is index.html was separate from the  frontend folder, can it be added to frontend folder and name the folder, landing page.

![Screenshot 2023-10-31 at 13-04-55 frontend used local storage in the login · Issue #17 · Endework_SEETHIO_LIVE](https://github.com/Endework/SEETHIO_LIVE/assets/131376909/a55a811a-5b4b-4ec5-be71-2815ad6b8d8d)

**Comment by Endework** [comment]
> The landing page file which is index.html was separate from the frontend folder, can it be added to frontend folder and name the folder, landing page.
> 
> ![Screenshot 2023-10-31 at 13-04-55 frontend used local storage in the login · Issue #17 · Endework_SEETHIO_LIVE](https://user-images.githubusercontent.com/131376909/279369400-a55a811a-5b4b-4ec5-be71-2815ad6b8d8d.png)

We can't do that, because the the Netlify host can't work that way. The index.html file should be available outside the folder.
