### ISSUE TITLE
Develop a user interface for login page

### ISSUE THREAD

**Issue by Endework** [Endework/SEETHIO_LIVE#2]

**Comment by oly-baby** [comment]
@Endework 
pls can you add a description to this issue

**Comment by Endework** [comment]
**Title:** Develop the User Interface for Login and Password Reset Flow

**Description:**
**Branch:** front-end
We need to develop the user interface for the login and password reset flow. This includes several subtasks:

1. **Develop the user interface for login page:** Create a user-friendly and intuitive login page where users can enter their credentials to access their account.

2. **Develop the user interface for forget password:** If users forget their password, they should be able to navigate to a page where they can enter their email to receive a password reset link.

3. **Develop the user interface for password reset email link:** Users should receive an email with a link that directs them to a page where they can reset their password.

4. **Develop the user interface for password reset page:** This page should allow users to enter a new password for their account.

5. **Develop password reset successful page:** Once the password has been reset, users should see a page confirming that their password has been successfully changed.

**Deadline:** [10/27/2022]

**Comment by Endework** [comment]
> @Endework pls can you add a description to this issue

Done

**Comment by Endework** [comment]
Completed
