### ISSUE TITLE
Develop a user interface for the landing page

### ISSUE THREAD

**Issue by Endework** [Endework/SEETHIO_LIVE#4]

**Comment by oly-baby** [comment]
@Endework 
pls add a description to this issue

**Comment by Endework** [comment]
**Title:** Develop the User Interface for the Landing Page

**Description:**
**Branch:** front-end
We need to develop the user interface for the landing page. This includes several subtasks:

1. **Develop the user interface for the landing page:** Create a visually appealing and user-friendly landing page.

2. **Navigation bar:** The landing page should have a navigation bar that allows users to navigate through different pages of the website.

3. **Attraction places slider:** The landing page should feature a slider that showcases different attraction places. This could be implemented using a carousel of images.

4. **How it works video:** The landing page should include a video that explains how the app works. This will help users understand the functionality and benefits of our app.

5. **Footer:** The landing page should also have a footer with relevant links and information about our company.

**Deadline:** [10/27/2022]

**Comment by Endework** [comment]
> @Endework pls add a description to this issue

Done

**Comment by oly-baby** [comment]
@Endework 

This is a frontend task

**Comment by Endework** [comment]
Yes I specified the branch

**Comment by Endework** [comment]
> @Endework
> 
> This is a frontend task

Yes I specified the branch already

**Comment by Austasty** [comment]
This is already completed
